"""Durable state for image generation.

Two tables only:

``image_generation_jobs`` is the unit of durable work. It survives a process
restart, is claimed with ``FOR UPDATE SKIP LOCKED``, and records what the user
approved (prompt, ratio, reference) plus where the result landed. It never
stores base64, provider responses, authentication material or signed URLs: the
generated bytes live in object storage and are referenced by an ``assets`` row.

``image_generation_budgets`` reserves a workspace's daily allowance *before* any
paid call, following the same UTC-period ledger shape already used for trend
sources. A job keeps the id of the ledger row it consumed, so a refund always
returns the reservation to the period that paid for it, even when the failure is
noticed on the following UTC day.

The status column is the durable record of whether the paid boundary was
crossed. ``SKIP LOCKED`` only protects the instant of the claim -- the lock ends
when the claim commits -- so the state machine, not the lock, is what keeps a
single request from being paid for twice::

    queued -> running -> provider_started -> succeeded | failed | cancelled

``running`` means a worker is preparing the call and nothing has been spent yet,
so it may be reclaimed once its lease expires. ``provider_started`` means the
request has left for the provider: it is never reclaimed, and a worker that dies
past this point leaves a job that is swept to ``failed`` with the ambiguous
``IMAGE_EXECUTION_UNKNOWN`` code rather than retried.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.projects.models import Project  # noqa: F401  registers ``projects`` for the FK

#: The lifecycle a job may take. ``queued`` is the only state a route creates.
JOB_STATUSES = (
    "queued",
    "running",
    "provider_started",
    "succeeded",
    "failed",
    "cancelled",
)

#: Terminal states: a job in one of these is never claimed again.
TERMINAL_JOB_STATUSES = frozenset({"succeeded", "failed", "cancelled"})

#: States a worker may take over. ``provider_started`` is deliberately absent:
#: past that point the money may already be spent, so no worker re-issues it.
RECLAIMABLE_JOB_STATUSES = frozenset({"queued", "running"})


def _uuid() -> str:
    return uuid.uuid4().hex


class ImageGenerationJob(Base):
    """One approved image request, executed exactly once by an external worker."""

    __tablename__ = "image_generation_jobs"

    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=_uuid)
    workspace_id: Mapped[str] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # The originating publication, when the job started from the Studio flow.
    # It is the durable parent a reload recovers from, so it points at a real
    # row: a deleted project clears the link instead of orphaning the job.
    project_id: Mapped[str | None] = mapped_column(
        ForeignKey("projects.id", ondelete="SET NULL"), nullable=True
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="queued", index=True)
    aspect_ratio: Mapped[str] = mapped_column(String(8), nullable=False)
    # The exact prompt the user confirmed, so a completed job is auditable.
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    negative_prompt: Mapped[str | None] = mapped_column(String(600), nullable=True)
    # A reference is always an asset this workspace already owns; never a URL
    # and never inline base64.
    reference_asset_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    model: Mapped[str] = mapped_column(String(160), nullable=False)
    asset_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    # Only a short, user-safe Spanish sentence: provider payloads may carry
    # prompts, balances or credentials.
    last_error_code: Mapped[str | None] = mapped_column(String(64), nullable=True)
    last_error: Mapped[str | None] = mapped_column(String(300), nullable=True)
    # The reservation this job consumed, bound to the exact period that paid.
    # A refund found by "today's ledger" would credit the wrong day whenever a
    # job created before UTC midnight fails after it.
    budget_id: Mapped[str | None] = mapped_column(
        ForeignKey("image_generation_budgets.id", ondelete="SET NULL"), nullable=True
    )
    #: The fencing token of the worker that currently owns this job. Every
    #: terminal write is conditioned on it, so a worker that lost its claim can
    #: neither overwrite a newer result nor refund a reservation twice.
    claim_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: When the request left for the provider. Non-null means "possibly paid".
    provider_started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        Index("ix_image_generation_jobs_status_created", "status", "created_at"),
        # A reload recovers the newest job of one project without scanning the
        # workspace, and without ever seeing another workspace's rows.
        Index(
            "ix_image_generation_jobs_workspace_project",
            "workspace_id",
            "project_id",
            "created_at",
        ),
        CheckConstraint(
            "aspect_ratio IN ('1:1', '4:5', '9:16')",
            name="ck_image_generation_job_ratio",
        ),
        CheckConstraint(
            "status IN ('queued', 'running', 'provider_started', "
            "'succeeded', 'failed', 'cancelled')",
            name="ck_image_generation_job_status",
        ),
        CheckConstraint("attempt_count >= 0", name="ck_image_generation_job_attempts"),
        # A job that reached the provider must say when. The sweeper reads this
        # column to decide that a call is unaccounted for rather than pending.
        CheckConstraint(
            "status <> 'provider_started' OR provider_started_at IS NOT NULL",
            name="ck_image_generation_job_provider_started",
        ),
    )


class ImageGenerationBudget(Base):
    """Per-workspace daily reservation ledger, consumed before any paid call."""

    __tablename__ = "image_generation_budgets"

    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=_uuid)
    workspace_id: Mapped[str] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False, index=True
    )
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    budget: Mapped[int] = mapped_column(Integer, nullable=False)
    consumed: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        UniqueConstraint(
            "workspace_id", "period_start", name="uq_image_generation_budget_period"
        ),
        CheckConstraint("budget > 0", name="ck_image_generation_budget_positive"),
        CheckConstraint(
            "consumed >= 0 AND consumed <= budget",
            name="ck_image_generation_budget_consumed",
        ),
    )
