import { useId, useState, useEffect, useCallback, useMemo, useRef } from "react";
import type { GeneratedSocialPost, VariationKind } from "@/types/artifact";
import { api, createIdempotencyKey } from "@/lib/api";
import { suggestCanvaTemplate } from "@/lib/canva-templates";
import type { ImageAspectRatio, VisualBrief } from "@/types/images";

interface Props {
  artifact: GeneratedSocialPost;
  onSave?: () => void;
  onVariation?: (kind: VariationKind) => void;
  onFeedback?: (rating: "useful" | "not_useful") => void;
  onCopy?: () => void;
}

export function GeneratedArtifactCard({
  artifact,
  onSave,
  onVariation,
  onFeedback,
  onCopy,
}: Props) {
  const titleId = useId();
  const [copyStatus, setCopyStatus] = useState("");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [imageError, setImageError] = useState("");
  const [aspectRatio, setAspectRatio] = useState<ImageAspectRatio>("1:1");
  const autoGeneratedRef = useRef(false);

  const generateImage = useCallback(
    async (ratio: ImageAspectRatio = "1:1") => {
      setIsGeneratingImage(true);
      setImageError("");
      try {
        const brief: VisualBrief = {
          subject: (
            artifact.visual_direction ||
            artifact.hook ||
            artifact.caption
          ).slice(0, 300),
          setting: "",
          style: "Fotografía publicitaria profesional, alta calidad, iluminación perfecta",
          palette: "",
          mood: "Vibrante, comercial",
          avoid: "baja calidad, texto distorsionado, borroso",
        };

        const preflight = await api.images.preflight({
          brief,
          aspect_ratio: ratio,
        });

        // Preflight is the step that authorizes and budgets the image: without
        // its token there is nothing to confirm, so the request stops here.
        if (!preflight.allowed || !preflight.approval_token) {
          throw new Error(
            preflight.message || "No puedes generar más imágenes por ahora."
          );
        }

        const idempotencyKey = createIdempotencyKey();
        const job = await api.images.createJob(
          {
            brief,
            aspect_ratio: ratio,
            confirmed: true,
            approval_token: preflight.approval_token,
          },
          { idempotencyKey }
        );

        let attempts = 0;
        const maxAttempts = 30;
        const checkStatus = async (): Promise<void> => {
          if (attempts >= maxAttempts) {
            throw new Error("Tiempo de espera agotado al generar la imagen.");
          }
          attempts++;
          const currentJob = await api.images.job(job.id);
          if (currentJob.status === "succeeded" && currentJob.image_url) {
            setImageUrl(currentJob.image_url);
            setIsGeneratingImage(false);
          } else if (
            currentJob.status === "failed" ||
            currentJob.status === "cancelled"
          ) {
            throw new Error(
              currentJob.error || "La generación de imagen no pudo completarse."
            );
          } else {
            await new Promise((resolve) => setTimeout(resolve, 1500));
            return checkStatus();
          }
        };

        await checkStatus();
      } catch (err: unknown) {
        const message =
          err instanceof Error
            ? err.message
            : "No se pudo generar la imagen automáticamente.";
        setImageError(message);
        setIsGeneratingImage(false);
      }
    },
    [artifact]
  );

  // Do not auto-generate images on mount to prioritize Canva templates and avoid rate limits


  async function copyArtifact() {
    try {
      await navigator.clipboard.writeText(
        [
          artifact.hook,
          artifact.caption,
          artifact.call_to_action,
          artifact.hashtags.join(" "),
          `Dirección visual: ${artifact.visual_direction}`,
        ]
          .filter(Boolean)
          .join("\n\n")
      );
      setCopyStatus("Contenido copiado.");
      onCopy?.();
    } catch {
      setCopyStatus(
        "No pudimos copiar el contenido. Selecciónalo y cópialo manualmente."
      );
    }
  }

  // The link is built from the subject of the post, not from whatever hashtags
  // came back: a technology post has to open technology templates.
  const canva = useMemo(() => suggestCanvaTemplate(artifact), [artifact]);
  const canvaUrl = canva.url;
  const extraHashtags = canva.hashtags.filter(
    (tag) =>
      !artifact.hashtags.some(
        (own) => own.replace(/^#/, "").toLowerCase() === tag.replace(/^#/, "").toLowerCase()
      )
  );

  return (
    <article className="artifact-card" aria-labelledby={titleId}>
      <p className="eyebrow">PROPUESTA GENERADA</p>
      <h2 id={titleId}>{artifact.hook}</h2>

      {/* Canva Template & Visual Recommendation */}
      <section
        style={{
          margin: "1rem 0",
          padding: "1rem",
          background: "linear-gradient(135deg, rgba(0, 196, 204, 0.08), rgba(123, 44, 191, 0.08))",
          borderRadius: "12px",
          border: "1px solid rgba(0, 196, 204, 0.3)",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "0.75rem",
          }}
        >
          <h3 style={{ margin: 0, fontSize: "0.95rem", fontWeight: 700, display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <span>🎨</span> Plantilla Canva para {canva.label}
          </h3>
          <a
            href={canvaUrl}
            target="_blank"
            rel="noreferrer"
            style={{
              padding: "0.4rem 0.85rem",
              fontSize: "0.8rem",
              fontWeight: 700,
              borderRadius: "8px",
              background: "linear-gradient(135deg, #00c4cc, #7b2cbf)",
              color: "#ffffff",
              textDecoration: "none",
              display: "inline-flex",
              alignItems: "center",
              gap: "0.35rem",
              boxShadow: "0 2px 8px rgba(0, 196, 204, 0.3)",
            }}
          >
            🚀 Abrir en Canva ↗
          </a>
        </div>

        <p style={{ margin: "0 0 0.75rem", fontSize: "0.85rem", color: "#d4d4d8", lineHeight: 1.5 }}>
          Búsqueda preparada para ti: «{canva.query}». Ábrela y edita la plantilla
          con tus colores y tipografías oficiales.
        </p>

        {extraHashtags.length ? (
          <p style={{ margin: "0 0 0.75rem", fontSize: "0.8rem", color: "#a1a1aa", lineHeight: 1.6 }}>
            Hashtags de {canva.label.toLowerCase()} para acompañar el post:{" "}
            <span style={{ color: "#e4e4e7", fontWeight: 600 }}>{extraHashtags.join(" ")}</span>
          </p>
        ) : null}

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "0.5rem", marginTop: "0.5rem" }}>
          <div style={{ padding: "0.6rem", background: "rgba(0,0,0,0.3)", borderRadius: "6px", border: "1px solid rgba(255,255,255,0.06)" }}>
            <span style={{ fontSize: "0.7rem", color: "#a1a1aa", textTransform: "uppercase", fontWeight: 600 }}>Titular para Canva</span>
            <p style={{ margin: "0.2rem 0 0", fontSize: "0.8rem", fontWeight: 600, color: "#ffffff" }}>«{artifact.hook}»</p>
          </div>
          <div style={{ padding: "0.6rem", background: "rgba(0,0,0,0.3)", borderRadius: "6px", border: "1px solid rgba(255,255,255,0.06)" }}>
            <span style={{ fontSize: "0.7rem", color: "#a1a1aa", textTransform: "uppercase", fontWeight: 600 }}>Botón / CTA</span>
            <p style={{ margin: "0.2rem 0 0", fontSize: "0.8rem", fontWeight: 600, color: "#38bdf8" }}>«{artifact.call_to_action}»</p>
          </div>
        </div>
      </section>

      <section>
        <h3>Texto</h3>
        <p>{artifact.caption}</p>
      </section>
      <section>
        <h3>Llamado a la acción</h3>
        <p>{artifact.call_to_action}</p>
      </section>
      <section>
        <h3>Dirección visual</h3>
        <p>{artifact.visual_direction}</p>
      </section>
      <p>{artifact.hashtags.join(" ")}</p>
      <div className="artifact-actions">
        <button type="button" onClick={onSave}>
          Guardar proyecto
        </button>
        <button type="button" onClick={() => void copyArtifact()}>
          Copiar contenido
        </button>
        <button type="button" onClick={() => onVariation?.("shorter")}>
          Más corto
        </button>
        <button type="button" onClick={() => onVariation?.("more_youthful")}>
          Más juvenil
        </button>
        <button type="button" onClick={() => onVariation?.("more_professional")}>
          Más profesional
        </button>
        <button type="button" onClick={() => onVariation?.("more_friendly")}>
          Más amigable
        </button>
        <button type="button" onClick={() => onFeedback?.("useful")}>
          Útil
        </button>
        <button type="button" onClick={() => onFeedback?.("not_useful")}>
          No útil
        </button>
      </div>
      <p
        role="status"
        aria-live="polite"
        style={{ minHeight: "1.2em", margin: "8px 0 0" }}
      >
        {copyStatus}
      </p>
      <small>
        Contenido generado como borrador. Revísalo antes de publicarlo.
      </small>
    </article>
  );
}
