import type { AppLocale } from "@/lib/i18n";

const es = {
  eyebrow: "TENDENCIAS",
  title: "Señales para tu próxima publicación",
  subtitle:
    "Explora tendencias observadas y verificables. Tú decides si tienen sentido para tu negocio.",
  lastUpdated: "Última actualización",
  noUpdate: "Aún no hay una recopilación",
  sources: "Ver fuentes",
  refresh: "Actualizar",
  refreshing: "Actualizando…",
  cooldown: "Próxima actualización disponible",
  scope: "Alcance",
  refreshScope: "El botón actualiza solo el alcance",
  evidence: "Evidencia",
  observed: "Observada",
  create: "Crear publicación",
  basedOnSignal: "Señal observada; no es una recomendación automática.",
  studioContext: "Contexto de tendencia",
  draftPrefix: "Publicación basada en la tendencia observada",
  relevance: "Relevancia para tu negocio",
  globalScore: "Score global",
  fresh: "Reciente",
  stale: "Antigua",
  loading: "Cargando tendencias",
  loadingCard: "Cargando señal",
  retry: "Reintentar",
  loadError: "No pudimos cargar las tendencias.",
  refreshError: "No pudimos actualizar las tendencias.",
  state: {
    fresh: "Las señales están actualizadas.",
    stale: "Estas señales son antiguas. Revisa sus fechas antes de usarlas.",
    empty: "No encontramos tendencias nuevas para este alcance.",
    disabled: "El análisis de tendencias está desactivado.",
    unconfigured: "Todavía no hay fuentes de tendencias configuradas.",
    degraded: "Algunas fuentes tuvieron problemas; mostramos la evidencia disponible.",
    failed: "La última recopilación no pudo completarse.",
  },
  stateHint: {
    empty: "Puedes volver a intentarlo cuando termine el cooldown.",
    disabled: "La información existente seguirá disponible cuando la capacidad se habilite.",
    unconfigured: "Un administrador debe configurar al menos una fuente segura.",
    failed: "Intenta nuevamente sin perder la información anterior.",
  },
  overview: {
    title: "Lo que hemos recopilado",
    signals: "Señales visibles",
    evidence: "Evidencias recopiladas",
    sourcesActive: "Fuentes activas",
    lastCollection: "Última recopilación",
    sourceHealth: "Estado de las fuentes",
    sourceHealthEmpty: "Todavía no hay fuentes declaradas.",
    scopeLabel: "Alcance de la próxima actualización",
  },
  empty: {
    title: "Todavía no hay señales que mostrar",
    lead: "Cuando termine una recopilación verás aquí cada señal con su evidencia, su fuente y su fecha.",
    steps: [
      "Revisa el alcance: la actualización recoge solo la región y la categoría que ves arriba.",
      "Comprueba las fuentes: solo las que están disponibles pueden aportar evidencia.",
      "Vuelve a intentarlo cuando termine el cooldown.",
    ],
    studioTitle: "Mientras tanto",
    studioLead: "Puedes crear contenido con el asistente sin esperar a una tendencia.",
    studioCta: "Abrir el Studio",
  },
  modal: {
    title: "Fuentes de tendencias",
    lead: "Estado público de las fuentes configuradas.",
    close: "Cerrar fuentes",
    configured: "Configurada",
    notConfigured: "Sin configurar",
    nextReset: "Próximo reset",
    empty: "No hay fuentes declaradas.",
    error: "No pudimos consultar las fuentes.",
    status: {
      available: "Disponible",
      degraded: "Degradada",
      quota_exhausted: "Cuota agotada",
      unavailable: "No disponible",
      unconfigured: "Sin configurar",
      disabled: "Desactivada",
    },
  },
};

export type TrendsCopy = typeof es;

const en: TrendsCopy = {
  eyebrow: "TRENDS",
  title: "Signals for your next post",
  subtitle:
    "Explore observed, verifiable trends. You decide whether they fit your business.",
  lastUpdated: "Last updated",
  noUpdate: "No collection yet",
  sources: "View sources",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  cooldown: "Next refresh available",
  scope: "Scope",
  refreshScope: "The button only refreshes the scope",
  evidence: "Evidence",
  observed: "Observed",
  create: "Create post",
  basedOnSignal: "Observed signal; it is not an automatic recommendation.",
  studioContext: "Trend context",
  draftPrefix: "Post based on the observed trend",
  relevance: "Business relevance",
  globalScore: "Global score",
  fresh: "Fresh",
  stale: "Stale",
  loading: "Loading trends",
  loadingCard: "Loading signal",
  retry: "Retry",
  loadError: "We could not load trends.",
  refreshError: "We could not refresh trends.",
  state: {
    fresh: "Signals are up to date.",
    stale: "These signals are old. Check their dates before using them.",
    empty: "No new trends were found for this scope.",
    disabled: "Trend analysis is disabled.",
    unconfigured: "Trend sources have not been configured yet.",
    degraded: "Some sources had issues; available evidence is still shown.",
    failed: "The latest collection could not be completed.",
  },
  stateHint: {
    empty: "You can try again after the cooldown.",
    disabled: "Existing information will remain available when the capability is enabled.",
    unconfigured: "An administrator must configure at least one safe source.",
    failed: "Try again without losing previous information.",
  },
  overview: {
    title: "What we have collected",
    signals: "Visible signals",
    evidence: "Collected evidence",
    sourcesActive: "Active sources",
    lastCollection: "Last collection",
    sourceHealth: "Source status",
    sourceHealthEmpty: "No sources are declared yet.",
    scopeLabel: "Scope of the next refresh",
  },
  empty: {
    title: "There are no signals to show yet",
    lead: "Once a collection finishes you will see each signal here with its evidence, source and date.",
    steps: [
      "Check the scope: the refresh only collects the region and category shown above.",
      "Check the sources: only available ones can contribute evidence.",
      "Try again once the cooldown ends.",
    ],
    studioTitle: "In the meantime",
    studioLead: "You can create content with the assistant without waiting for a trend.",
    studioCta: "Open the Studio",
  },
  modal: {
    title: "Trend sources",
    lead: "Public status of configured sources.",
    close: "Close sources",
    configured: "Configured",
    notConfigured: "Not configured",
    nextReset: "Next reset",
    empty: "No sources are declared.",
    error: "We could not load sources.",
    status: {
      available: "Available",
      degraded: "Degraded",
      quota_exhausted: "Quota exhausted",
      unavailable: "Unavailable",
      unconfigured: "Unconfigured",
      disabled: "Disabled",
    },
  },
};

const pt: TrendsCopy = {
  eyebrow: "TENDÊNCIAS",
  title: "Sinais para sua próxima publicação",
  subtitle:
    "Explore tendências observadas e verificáveis. Você decide se fazem sentido para seu negócio.",
  lastUpdated: "Última atualização",
  noUpdate: "Ainda não há coleta",
  sources: "Ver fontes",
  refresh: "Atualizar",
  refreshing: "Atualizando…",
  cooldown: "Próxima atualização disponível",
  scope: "Escopo",
  refreshScope: "O botão atualiza apenas o escopo",
  evidence: "Evidência",
  observed: "Observada",
  create: "Criar publicação",
  basedOnSignal: "Sinal observado; não é uma recomendação automática.",
  studioContext: "Contexto da tendência",
  draftPrefix: "Publicação baseada na tendência observada",
  relevance: "Relevância para seu negócio",
  globalScore: "Score global",
  fresh: "Recente",
  stale: "Antiga",
  loading: "Carregando tendências",
  loadingCard: "Carregando sinal",
  retry: "Tentar novamente",
  loadError: "Não foi possível carregar as tendências.",
  refreshError: "Não foi possível atualizar as tendências.",
  state: {
    fresh: "Os sinais estão atualizados.",
    stale: "Estes sinais são antigos. Confira as datas antes de usá-los.",
    empty: "Nenhuma tendência nova foi encontrada para este escopo.",
    disabled: "A análise de tendências está desativada.",
    unconfigured: "As fontes de tendências ainda não foram configuradas.",
    degraded: "Algumas fontes tiveram problemas; mostramos a evidência disponível.",
    failed: "A última coleta não pôde ser concluída.",
  },
  stateHint: {
    empty: "Você pode tentar novamente quando o cooldown terminar.",
    disabled: "As informações existentes continuarão disponíveis quando a função for ativada.",
    unconfigured: "Um administrador deve configurar pelo menos uma fonte segura.",
    failed: "Tente novamente sem perder as informações anteriores.",
  },
  overview: {
    title: "O que já coletamos",
    signals: "Sinais visíveis",
    evidence: "Evidências coletadas",
    sourcesActive: "Fontes ativas",
    lastCollection: "Última coleta",
    sourceHealth: "Status das fontes",
    sourceHealthEmpty: "Ainda não há fontes declaradas.",
    scopeLabel: "Escopo da próxima atualização",
  },
  empty: {
    title: "Ainda não há sinais para mostrar",
    lead: "Quando uma coleta terminar você verá aqui cada sinal com sua evidência, sua fonte e sua data.",
    steps: [
      "Confira o escopo: a atualização coleta apenas a região e a categoria mostradas acima.",
      "Confira as fontes: só as disponíveis podem trazer evidência.",
      "Tente novamente quando o cooldown terminar.",
    ],
    studioTitle: "Enquanto isso",
    studioLead: "Você pode criar conteúdo com o assistente sem esperar por uma tendência.",
    studioCta: "Abrir o Studio",
  },
  modal: {
    title: "Fontes de tendências",
    lead: "Status público das fontes configuradas.",
    close: "Fechar fontes",
    configured: "Configurada",
    notConfigured: "Não configurada",
    nextReset: "Próximo reset",
    empty: "Não há fontes declaradas.",
    error: "Não foi possível consultar as fontes.",
    status: {
      available: "Disponível",
      degraded: "Degradada",
      quota_exhausted: "Cota esgotada",
      unavailable: "Indisponível",
      unconfigured: "Não configurada",
      disabled: "Desativada",
    },
  },
};

export const trendsCopy: Record<AppLocale, TrendsCopy> = { es, en, pt };
